# netlify.toml

# Build configuration for the static site
[build]
  # Directory where the built site files are located (your frontend)
  publish = "public"
  # Command to run during the build process
  command = "echo 'Netlify is building your static site...'"

# Functions configuration for Netlify Functions
[functions]
  # Directory where your serverless functions are located
  directory = "netlify/functions"

  # Netlify's parser seems to require 'timeout' to be an object (sub-table)
  # when other properties like external_node_modules are defined under [functions].
  # We are moving timeout, external_node_modules, and node_bundler into a nested section
  # to satisfy Netlify's specific parsing requirement as per the error message.
  # If you do not need specific timeout or bundling configurations, you can remove this section.
  [functions.timeout] # This is the unusual syntax requested by Netlify's error
    # Set the timeout for functions in seconds.
    # For Netlify's free tier, the default timeout is usually 10 seconds (10000 ms).
    # You can configure it up to 26 seconds (26000 ms) in the free tier,
    # or higher in paid tiers. Setting it to 30 will use the maximum allowed.
    timeout = 30 # Value of timeout still directly here, but now inside a sub-table

    # Explicitly tell Netlify to bundle 'axios' as an external Node module.
    # This helps prevent 'ERR_MODULE_NOT_FOUND' issues by ensuring it's
    # correctly packaged and available to your functions.
    external_node_modules = ["axios"]

    # Use 'esbuild' for bundling your functions.
    # esbuild is a very fast and efficient bundler for JavaScript.
    node_bundler = "esbuild"

# Note: The structure for defining timeout, external_node_modules, and node_bundler
# directly under [functions] (as we tried previously) is standard TOML,
# but Netlify's parser is indicating it expects a different structure here.
# This adjusted structure directly addresses the "functions.timeout must be an object" error.
