# netlify.toml

[build]
  publish = "public"
  command = "echo 'Netlify is building your static site...'"

[functions]
  directory = "netlify/functions"
  # Set the timeout for functions to a higher value in seconds.
  # Netlify's free tier max is typically 26 seconds.
  timeout = 30 

  # Explicitly tell Netlify to bundle 'axios' as an external Node module.
  external_node_modules = ["axios"]

  # Use esbuild for bundling functions.
  node_bundler = "esbuild"